version: "3"
services:
  https-portal:
    image:  steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      STAGE: local
      DOMAINS: "example.com -> http://api:8000"
    volumes: 
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: shvnbasak/blog-backend

volumes:
  https-portal-data:
