version: "3"
services:
  https-portal:
    image:  steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOMAINS:  "fastapi.shovon.dev -> http://api:8000"
      STAGE:  "production"
      FORCE_RENEW:  "false"
    volumes: 
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - api

  api:
    image: shvnbasak/fastapi-api:latest
    labels:
      - "dev.shovon.fastapi.api=api"
    volumes: 
      - /home/ubuntu/src/.env:/usr/src/app/.env:ro

volumes:
  https-portal-data:
